[package]
name = "lan-mouse-tray"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "macros", "sync"] }
zbus = { version = "5", default-features = false, features = ["tokio"] }
futures-util = "0.3"
