[package]
name = "battery-tray"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-rs = "0.20"
futures-util = "0.3"
pango = "0.20"
pangocairo = "0.20"
tokio = { version = "1", features = ["rt", "macros", "time"] }
zbus = { version = "5", default-features = false, features = ["tokio"] }
